Remove invalid python from read me
couple of the readme examples contained invalid python, `04` instead of `4` raises a syntax exception:

```
◤ ~ python
Python 3.6.6 (default, Jun 27 2018, 13:11:40) 
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> foo = 04
  File "<stdin>", line 1
    foo = 04
           ^
SyntaxError: invalid token
>>> 
```